FROM debian:latest

RUN apt update
RUN apt install make
RUN apt install -y --no-install-recommends gcc binutils bison
RUN apt install -y --no-install-recommends ruby
RUN apt install -y --no-install-recommends wget
RUN apt install -y --no-install-recommends libc6-dev

